name: plasticity-dev
channels:
  - default
  - anaconda
  - conda-forge

dependencies:
  # required
  - numpy>=1.15
  - python=3
  - scikit-learn>=0.20.3

  # building
  - pkgconfig
  - cython>=0.29
  - eigen

  # documentation
  - breathe>=4.14.1
