name: plasticity C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ${{ matrix.cfg.os }}
    name: ${{ matrix.cfg.os }}@${{ matrix.cfg.cxx }}-${{ matrix.cfg.cpp-version }}

    strategy:
      matrix:
        cfg:
#          - {os: ubuntu-16.04, cc: gcc, cxx: g++, cpp-version: 4.8} # WORKS
#          - {os: ubuntu-16.04, cc: gcc, cxx: g++, cpp-version: 4.9} # WORKS
#          - {os: ubuntu-16.04, cc: gcc, cxx: g++, cpp-version: 5.0} # WORKS
#          - {os: ubuntu-16.04, cc: gcc, cxx: g++, cpp-version: 6.0} # WORKS
#          - {os: ubuntu-16.04, cc: gcc, cxx: g++, cpp-version: 7.0} # WORKS
#
#          - {os: ubuntu-18.04, cc: gcc, cxx: g++, cpp-version: 7.0} # WORKS
#          - {os: ubuntu-18.04, cc: gcc, cxx: g++, cpp-version: 8.0} # WORKS
#          - {os: ubuntu-18.04, cc: gcc, cxx: g++, cpp-version: 9.0} # WORKS
#
#          - {os: ubuntu-16.04, cc: gcc, cxx: g++, cpp-version: 4.8} # WORKS
#          - {os: ubuntu-16.04, cc: gcc, cxx: g++, cpp-version: 4.9} # WORKS
#          - {os: ubuntu-16.04, cc: gcc, cxx: g++, cpp-version: 5.0} # WORKS
#          - {os: ubuntu-16.04, cc: gcc, cxx: g++, cpp-version: 6.0} # WORKS
#          - {os: ubuntu-20.04, cc: gcc, cxx: g++, cpp-version: 7.0} # WORKS
#          - {os: ubuntu-20.04, cc: gcc, cxx: g++, cpp-version: 8.0} # WORKS
#          - {os: ubuntu-20.04, cc: gcc, cxx: g++, cpp-version: 9.0} # WORKS
#          - {os: ubuntu-20.04, cc: gcc, cxx: g++, cpp-version: 10} # WORKS


          - {os: ubuntu-16.04, cc: clang, cxx: clang, cpp-version: 3.6}
          - {os: ubuntu-16.04, cc: clang, cxx: clang, cpp-version: 3.8}
          - {os: ubuntu-16.04, cc: clang, cxx: clang, cpp-version: 3.9}
          - {os: ubuntu-16.04, cc: clang, cxx: clang, cpp-version: 4.0}
          - {os: ubuntu-16.04, cc: clang, cxx: clang, cpp-version: 5.0}
          - {os: ubuntu-18.04, cc: clang, cxx: clang, cpp-version: 6.0}
          - {os: ubuntu-18.04, cc: clang, cxx: clang, cpp-version: 7.0}


#          - {os: windows-latest, cc: cl, cxx: cl, cpp-version: latest}
#          - {os: windows-latest, cc: clang-cl, cxx: clang-cl, cpp-version: latest}
#          - {os: windows-latest, cc: gcc, cxx: g++, cpp-version: latest}

#          - {os: macos-latest, cc: gcc, cxx: gcc, cpp-version: 7.0}
#          - {os: macos-latest, cc: clang, cxx: clang, cpp-version: 7.0}


#          - {os: ubuntu-20.04, cc: gcc, cxx: g++, cpp-version: 9.0} # WORKS
#          - {os: ubuntu-20.04, cc: gcc, cxx: g++, cpp-version: 9.0} # WORKS
#          - {os: ubuntu-20.04, cc: gcc, cxx: g++, cpp-version: 9.0} # WORKS

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Setting env variables
      run: |
        echo "WORKSPACE=${{ github.workspace }}/.." >> $GITHUB_ENV
        echo "VCPKG_ROOT=$env:WORKSPACE/vcpkg" >> $GITHUB_ENV
        echo "VCPKG_DEFAULT_TRIPLET=x64-windows" >> $GITHUB_ENV

    - name: Get latest CMake and Ninja
      # Using 'latest' branch, the latest CMake and ninja are installed.
      uses: lukka/get-cmake@latest

    - name: Install (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ${{ matrix.cfg.cxx }}-${{ matrix.cfg.cpp-version }}

        echo "CC=${{ matrix.cfg.cc }}-${{ matrix.cfg.cpp-version }}" >> $GITHUB_ENV
        echo "CXX=${{ matrix.cfg.cxx }}-${{ matrix.cfg.cpp-version }}" >> $GITHUB_ENV

        # Install the Eigen Library
        sudo apt-get install -y libeigen3-dev

    - name: Install (macOS)
      if: runner.os == 'macOS'
      run: |
        brew reinstall ${{ matrix.cfg.cxx }}@${{ matrix.cfg.cpp-version }}

        echo "CC=${{ matrix.cfg.cc }}-${{ matrix.cfg.cpp-version }}" >> $GITHUB_ENV
        echo "CXX=${{ matrix.cfg.cxx }}-${{ matrix.cfg.cpp-version }}" >> $GITHUB_ENV

        # Install the Eigen Library
        brew install eigen

    - name: Install (Windows)
      if: runner.os == 'Windows'
      run: |

        # Install vcpkg
        cd $env:WORKSPACE
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout --force 2020.01
        .\bootstrap-vcpkg.bat

        # Install the Eigen Library
        .\vcpkg.exe install eigen3:$env:VCPKG_DEFAULT_TRIPLET

    - name: 'Configure build (Windows)'
      if: runner.os == 'Windows'
      run: |
        cd ${{ github.workspace }}
        mkdir buildDirectory_debug
        cd buildDirectory_debug
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="$env:VCPKG_DEFAULT_TRIPLET" -DBUILD_DOCS=OFF -DBUILD_TEST=ON -DOMP=ON -DPYWRAP=OFF
        cd ..
        mkdir buildDirectory_release
        cd buildDirectory_release
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="$env:VCPKG_DEFAULT_TRIPLET" -DBUILD_DOCS=OFF -DBUILD_TEST=ON -DOMP=ON -DPYWRAP=OFF
        cd ..

    - name: 'Configure build (Unix)'
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        cd ${{ github.workspace }}
        mkdir buildDirectory_debug
        cd buildDirectory_debug
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE="Debug" -DBUILD_DOCS=OFF -DBUILD_TEST=ON -DOMP=OFF -DPYWRAP=OFF
        cd ..
        mkdir buildDirectory_release
        cd buildDirectory_release
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE="Release" -DBUILD_DOCS=OFF -DBUILD_TEST=ON -DOMP=OFF -DPYWRAP=OFF
        cd ..

    - name: 'Build'
      run: |
        cd ${{ github.workspace }}
        cd buildDirectory_debug
        cmake --build . --target install -- -j8
        cd ..
        cd buildDirectory_release
        cmake --build . --target install -- -j8
        cd ..
